DO $$ BEGIN
  ALTER TYPE "WorkOrderStatus" ADD VALUE 'PAUSED';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "WorkOrderStatus" ADD VALUE 'VALIDATED';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "notifyStartTime" TEXT DEFAULT '08:00',
  ADD COLUMN IF NOT EXISTS "notifyEndTime" TEXT DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS "notifyDays" TEXT DEFAULT '1,2,3,4,5',
  ADD COLUMN IF NOT EXISTS "telegramChatId" TEXT,
  ADD COLUMN IF NOT EXISTS "telegramEnabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "WorkOrder"
  ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "pausedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "validatedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "totalWorkSeconds" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "lastResumedAt" TIMESTAMP(3);
