import {
  BarChart3,
  Car,
  ClipboardCheck,
  Activity,
  FileText,
  Gauge,
  Leaf,
  TreePalm,
  LayoutDashboard,
  Package,
  Receipt,
  Rows3,
  Settings,
  UserCog,
  Wrench,
  Siren,
} from "lucide-react";

export const navigation = [
  { name: "Dashboard", href: "/", meta: "Visão diária", icon: LayoutDashboard, color: "bg-teal-400/15 text-teal-200" },
  { name: "Tickets", href: "/tickets", meta: "Avarias e tempos", icon: Siren, color: "bg-red-400/15 text-red-200" },
  { name: "Despesas", href: "/despesas", meta: "Faturas e recibos", icon: Receipt, color: "bg-amber-400/15 text-amber-200" },
  { name: "Analises", href: "/analises", meta: "Fornecedores e custos", icon: BarChart3, color: "bg-emerald-400/15 text-emerald-200" },
  { name: "KPIs", href: "/kpis", meta: "Fiabilidade e tempos", icon: Activity, color: "bg-sky-400/15 text-sky-200" },
  { name: "Férias", href: "/ferias", meta: "Mapa da equipa", icon: TreePalm, color: "bg-emerald-400/15 text-emerald-200" },
  { name: "Ambiental", href: "/ambiental", meta: "Temperatura e pressão", icon: Leaf, color: "bg-lime-400/15 text-lime-200" },
  { name: "Tarefas", href: "/tarefas", meta: "Recorrencias", icon: ClipboardCheck, color: "bg-teal-400/15 text-teal-200" },
  { name: "Manutenção", href: "/manutenção", meta: "Ativos e infraestrutura", icon: Wrench, color: "bg-cyan-400/15 text-cyan-200" },
  { name: "Equipamentos", href: "/equipamentos", meta: "Cadastro e planos", icon: Settings, color: "bg-orange-400/15 text-orange-200" },
  { name: "Frota", href: "/frota", meta: "Veiculos e quilometros", icon: Car, color: "bg-blue-400/15 text-blue-200" },
  { name: "Calibracao", href: "/calibracao", meta: "Certificados", icon: Gauge, color: "bg-lime-400/15 text-lime-200" },
  { name: "Inventario", href: "/inventario", meta: "Peças e consumíveis", icon: Package, color: "bg-amber-400/15 text-amber-200" },
  { name: "Checklists", href: "/checklists", meta: "Modelos por tipo", icon: Rows3, color: "bg-sky-400/15 text-sky-200" },
  { name: "Documentos", href: "/documentos", meta: "Garantias e contratos", icon: FileText, color: "bg-rose-400/15 text-rose-200" },
  { name: "Acessos", href: "/acessos", meta: "Perfis e permissões", icon: UserCog, color: "bg-violet-400/15 text-violet-200" },
];
